### ISSUE TITLE
GIVpower Boosting | How should GIVbacks be afftect by the project's rank?

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1681]
GIVbacks factor calculation sheet:
https://docs.google.com/spreadsheets/d/1yz_6sgFmEXgGU9BgeRtgVALQlNFWJMUkxddpTlG2Krs/edit#gid=0

@divine-comedian & I were talking about having the min GIVbacks factor 50% & the max GIVbacks factor 85%

Looking for some feedback on this from @mohammadranjbarz @WhyldWanderer @GriffGreen

**Comment by GriffGreen** [comment]
85% seems really high. 

I think making it range between 80% and 60% seems best at launch and then we see how everything works... I played with the spreadsheet a little:

https://docs.google.com/spreadsheets/d/1QxXXMGoT_ubKodMaUH2_ijG5bcByhkKr0jbV6Vis91c/edit#gid=0

**Comment by divine-comedian** [comment]
I like a minimum spread of 30% - The greater the spread means a wider field of GIVbacks incentives that projects can compete to offer their donors.

**Comment by laurenluz** [comment]
so 80% to 50%?

**Comment by laurenluz** [comment]
ok! @divine-comedian @GriffGreen & I just had a quick call about this, and we're good with this as a "good enough for now, safe enough to try" spec.

@mohammadranjbarz can you work w/ @divine-comedian to implement this so we have it ready after boosting launch?

@divine-comedian is drafting an explanation of this in the docs.

@laurenluz created a [forum post](https://forum.giveth.io/t/givpower-how-project-ranking-should-affect-givbacks/869) to get soft consensus

**Comment by divine-comedian** [comment]
@mohammadranjbarz 

The main changes will be to the calculate givbacks API

Instead of a constant GIVbacks factor each project will have a unique factor depending on its GIVpower rank. 

in the API parameters instead of one GIVbacks factor we will need to be able to set the maximum factor and the minimum factor

in the calculation we subtract the maximum factor by the minimum factor to get the 'spread" - we divide the spread by the number of ranked projects on the platform - from this we derive the change of givbacks factor from one rank to the next one, this is the "increment". 

the top ranked project gets the maximum factor, the bottom ranked project gets the minimum factor

each rank up from the bottom gets an increment to its givback factor based on the calculation I mentioned earlier.

![image](https://user-images.githubusercontent.com/67759413/197902726-f96bcf3c-e865-447e-b7fb-5aa0c2783bc3.png)

check out this spreadsheet - you can copy it to your own files and play with it:
https://docs.google.com/spreadsheets/d/1yz_6sgFmEXgGU9BgeRtgVALQlNFWJMUkxddpTlG2Krs/edit?usp=sharing

----

more importantly the math for when we project to spend more GIVbacks than we have to distribute we have to implement a slightly different formula:

Here is the old formula for reference:
![image](https://user-images.githubusercontent.com/67759413/197903959-b1670c5b-7610-4542-8be2-5e539fc36f88.png)

we simply update the values v and V for:

v = the estimated amount of GIVbacks the project would normally receive
V = the estimated total amount of GIVbacks from all projects for that round

---

does this make sense?

**Comment by mohammadranjbarz** [comment]
Thanks @divine-comedian  for clarifying the issue, it totally makes sense, just one question what givFactor should be for trace donations?
I heard that @GriffGreen  said we might not use Trace anymore, how about exclude all trace donations from givback calculation and make project smaller?

**Comment by divine-comedian** [comment]
> Thanks @divine-comedian  for clarifying the issue, it totally makes sense, just one question what givFactor should be for trace donations?
> I heard that @GriffGreen once said we might not use Trace anymore, how about exclude all trace donations from givback calculation and make project smaller?

yes you can remove trace donations - we have removed the ability to make donations and are in the process of shutting it down.

**Comment by mohammadranjbarz** [comment]
@divine-comedian 

It's implemented and deployed on Staging, you can reach it here
https://givback.develop.giveth.io/staging/api-docs

As we don't have powerRank in production so I connected this to impact-graph staging so you would see different result in 
https://givback.develop.giveth.io/staging/api-docs and https://givback.develop.giveth.io/api-docs

As because we have less donations in staging server you would expand the range for instance I tested it and just got 10 donations, but you can donate to projects and see the changes


<img width="1423" alt="Screen Shot 1401-08-12 at 17 08 21" src="https://user-images.githubusercontent.com/9850545/199742633-d7fa7bf2-a13c-4afa-9734-b62fe7af08e5.png">


As you see in /calculate response you will see these 3 extra fields

* **totalDonationsUsdValueAfterGivFactor**
As the donations are group by donor, and they may have donated to some project with different power ranks so we just say what is the dollar value after affecting givFactor,  but if you want to see the power rank of project of every donation you should use https://givback.develop.giveth.io/staging/api-docs/#/default/get_eligible_donations

* **averageGivbackFactor**
This field is just  come from dividing `totalDonationsUsdValueAfterGivFactor` to `totalDonationsUsdValue`


If you had more question please ask me to make sure it's clear for both of us

**Comment by divine-comedian** [comment]
in https://givback.develop.giveth.io/staging/api-docs/#/default/get_eligible_donations

we should add 1 more column that shows the givbacksFactor for each donation - this is based on the powerRank of the project

**Comment by mohammadranjbarz** [comment]
> testing on https://givback.develop.giveth.io/staging/api-docs/#/default/get_calculate
> 
> I ran a simulation with these params:
> 
> ![image](https://user-images.githubusercontent.com/67759413/200349294-d439909f-f5a9-47fd-9772-c189d10ad8a8.png)
> 
> givDistributed	givPrice	givbackUsdValue	giverAddress	giverEmail	giverName	totalDonationsUsdValueAfterGivFactor	totalDonationsUsdValue	averageGivbackFactor	givback
> 2074	0.03	40.97	0x871cd6353b803ceceb090bb827ecb2f361db81ab		Alireza Sharifpour	40.97	56.37	0.73	1365.67
> 2074	0.03	21.04	0x10a84b835c5df26f2a380b3e00bcc84a66cd2d34		Ram Ramez	21.04	28.76	0.73	701.33
> 2074	0.03	0.13	0x5ac583feb2b1f288c0a51d6cdca2e8c814bfe93b		Mohammad Ranjbar	0.13	0.16	0.81	4.33
> 2074	0.03	0.06	0x2a7ae8118c11b5139afaf80b27ff59235593e97e		Tosin Ariyo	0.06	0.07	0.86	2
> in part of my result you can see some donations have an averageGIVbackFactor greater than the maximum, how is that possible?

I think it's because I limited the precise to two digits for donations and in small amounts it changes the calculation a little bit, so it became grater than  max give factor, once I add the givbacks factor to eligible donations response we know it better, I will let you know after I do it

**Comment by mohammadranjbarz** [comment]
@divine-comedian 
Done.
Now the donation in  response of eligible-donations would be something like this:

```
 {
    "amount": 0.01,
    "currency": "ETH",
    "createdAt": "2022-11-01-12:26:51",
    "valueUsd": 15.9414,
    "valueUsdAfterGivbackFactor": 8.967,
    "givbackFactor": 0.5625,
    "powerRank": 20,
    "giverAddress": "0x871cd6353b803ceceb090bb827ecb2f361db81ab",
    "txHash": "0x8f61f983daeaf4cb9c17a3054681ff6a1971467a400710c756b2da8ea21f9800",
    "network": "xDAI",
    "source": "giveth.io",
    "giverName": "Alireza Sharifpour",
    "giverEmail": null,
    "projectLink": "https://giveth.io/project/the-discalced-hermits-of-our-lady-of-mount-carmel"
  }
```

**Comment by divine-comedian** [comment]
> @divine-comedian Done. Now the donation in response of eligible-donations would be something like this:
> 
> ```
>  {
>     "amount": 0.01,
>     "currency": "ETH",
>     "createdAt": "2022-11-01-12:26:51",
>     "valueUsd": 15.9414,
>     "valueUsdAfterGivbackFactor": 8.967,
>     "givbackFactor": 0.5625,
>     "powerRank": 20,
>     "giverAddress": "0x871cd6353b803ceceb090bb827ecb2f361db81ab",
>     "txHash": "0x8f61f983daeaf4cb9c17a3054681ff6a1971467a400710c756b2da8ea21f9800",
>     "network": "xDAI",
>     "source": "giveth.io",
>     "giverName": "Alireza Sharifpour",
>     "giverEmail": null,
>     "projectLink": "https://giveth.io/project/the-discalced-hermits-of-our-lady-of-mount-carmel"
>   }
> ```

Amazing - So now we'll need to find the average of all givBackFactor in `eligible-donations` for each donor over the given time period and show it in `calculate` under `averageGIVbackFactor`. 


Also it would be useful to think of a way to show the # of ranked projects on the platform at a given time. Perhaps we put in a single date and we show the # of ranked projects for that round the date is inside of? 

This will help us for stats and also testing the algorithm. I'll break this into a few more issues.

**Comment by divine-comedian** [comment]
> @divine-comedian For knowing what is the top power rank
> 
> ```
> curl --location --request POST 'https://serve.giveth.io/graphql' \
> --header 'Accept-Encoding: gzip, deflate, br' \
> --header 'Content-Type: application/json' \
> --header 'Accept: application/json' \
> --header 'Connection: keep-alive' \
> --header 'DNT: 1' \
> --header 'Origin: http://localhost:4000' \
> --header 'VERCEL_KEY: 123' \
> --data-raw '{"query":"    query {\n        getTopPowerRank\n        }","variables":{}}'
> ```
> 
> You can put it directly in terminal or import it in postman
> 
>     * **Postman**
> 
> 
> <img alt="Screen Shot 1401-08-18 at 17 31 06" width="960" src="https://user-images.githubusercontent.com/9850545/200857172-3101baee-38e5-470e-a0a6-5d690a73e529.png">
> 
>     * **Terminal**
> 
> 
> <img alt="Screen Shot 1401-08-18 at 17 29 50" width="1260" src="https://user-images.githubusercontent.com/9850545/200856913-0a818ef9-c9db-4002-aa0e-3c0a49dc7d40.png">

This is sort of useful - so we can see the total amount of ranks at the current time. This is a bit confusing since the top rank is actually 1 and the bottom rank is the greatest number rank in the system. 

what would be nice is a way to see a full list of ranks and the associated project URL for a given round or given point in time

**Comment by mohammadranjbarz** [comment]
> > @divine-comedian For knowing what is the top power rank
> > ```
> > curl --location --request POST 'https://serve.giveth.io/graphql' \
> > --header 'Accept-Encoding: gzip, deflate, br' \
> > --header 'Content-Type: application/json' \
> > --header 'Accept: application/json' \
> > --header 'Connection: keep-alive' \
> > --header 'DNT: 1' \
> > --header 'Origin: http://localhost:4000' \
> > --header 'VERCEL_KEY: 123' \
> > --data-raw '{"query":"    query {\n        getTopPowerRank\n        }","variables":{}}'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You can put it directly in terminal or import it in postman
> > ```
> > * **Postman**
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > <img alt="Screen Shot 1401-08-18 at 17 31 06" width="960" src="https://user-images.githubusercontent.com/9850545/200857172-3101baee-38e5-470e-a0a6-5d690a73e529.png">
> > ```
> > * **Terminal**
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > <img alt="Screen Shot 1401-08-18 at 17 29 50" width="1260" src="https://user-images.githubusercontent.com/9850545/200856913-0a818ef9-c9db-4002-aa0e-3c0a49dc7d40.png">
> 
> This is sort of useful - so we can see the total amount of ranks at the current time. This is a bit confusing since the top rank is actually 1 and the bottom rank is the greatest number rank in the system.
> 
> what would be nice is a way to see a full list of ranks and the associated project URL for a given round or given point in time

Yeah you know our naming was not good when implementing that, our mistake.

And the other webs ervice that you mentioned, I implemented that now, you can see it 
https://givback.develop.giveth.io/staging/api-docs/#/default/get_getAllProjectsSortByRank

it return all projects that have totalPower>0 but for project with totalPower=0 that all of them have same rank, we don't return them all, response sample:
```
[
  {
    "id": "911",
    "title": "Cascades Raptor Center",
    "slug": "cascades-raptor-center",
    "verified": true,
    "projectPower": {
      "totalPower": 713059.664628,
      "powerRank": 1,
      "round": 2203
    },
    "link": "https://staging.giveth.io/project/cascades-raptor-center"
  },
  {
    "id": "918",
    "title": "Boys & Girls Club of Greater Lowell",
    "slug": "boys-and-girls-club-of-greater-lowell",
    "verified": true,
    "projectPower": {
      "totalPower": 365011.007904,
      "powerRank": 2,
      "round": 2203
    },
    "link": "https://staging.giveth.io/project/boys-and-girls-club-of-greater-lowell"
  },
  {
    "id": "82",
    "title": "How many photos is too many photos?",
    "slug": "how-many-photos-is-too-many-photos",
    "verified": true,
    "projectPower": {
      "totalPower": 229567.327718,
      "powerRank": 3,
      "round": 2203
    },
    "link": "https://staging.giveth.io/project/how-many-photos-is-too-many-photos"
  },
  {
    "id": "223521",
    "title": "maryam jafarymehr",
    "slug": "maryam-jafarymehr",
    "verified": true,
    "projectPower": {
      "totalPower": 62117.672812,
      "powerRank": 4,
      "round": 2203
    },
    "link": "https://staging.giveth.io/project/maryam-jafarymehr"
  },
  {
    "id": "223531",
    "title": "testfilterr",
    "slug": "testfilterr",
    "verified": true,
    "projectPower": {
      "totalPower": 41301.33834,
      "powerRank": 5,
      "round": 2203
    },
    "link": "https://staging.giveth.io/project/testfilterr"
  },
  {
    "id": "137",
    "title": "test issue 173",
    "slug": "test-issue-173",
    "verified": true,
    "projectPower": {
      "totalPower": 37881.890258,
      "powerRank": 6,
      "round": 2203
    },
    "link": "https://staging.giveth.io/project/test-issue-173"
  },
  {
    "id": "2032",
    "title": "Unique Care Connect, Inc.",
    "slug": "unique-care-connect-inc",
    "verified": true,
    "projectPower": {
      "totalPower": 21826.872132999997,
      "powerRank": 7,
      "round": 2203
    },
    "link": "https://staging.giveth.io/project/unique-care-connect-inc"
  },
  {
    "id": "917",
    "title": "Eyebeam",
    "slug": "eyebeam",
    "verified": true,
    "projectPower": {
      "totalPower": 18057.05945,
      "powerRank": 8,
      "round": 2203
    },
    "link": "https://staging.giveth.io/project/eyebeam"
  },
  {
    "id": "936",
    "title": "Thousand Currents",
    "slug": "thousand-currents",
    "verified": true,
    "projectPower": {
      "totalPower": 14258.017980000002,
      "powerRank": 9,
      "round": 2203
    },
    "link": "https://staging.giveth.io/project/thousand-currents"
  },
  {
    "id": "914",
    "title": "Boulder JCC",
    "slug": "boulder-jcc",
    "verified": true,
    "projectPower": {
      "totalPower": 11636.5776,
      "powerRank": 10,
      "round": 2203
    },
    "link": "https://staging.giveth.io/project/boulder-jcc"
  },
  {
    "id": "931",
    "title": "Harper's Playground",
    "slug": "harpers-playground",
    "verified": true,
    "projectPower": {
      "totalPower": 11431.153596,
      "powerRank": 11,
      "round": 2203
    },
    "link": "https://staging.giveth.io/project/harpers-playground"
  },
  {
    "id": "904",
    "title": "SynGAP Research Fund (SRF)",
    "slug": "syngap-research-fund-srf",
    "verified": true,
    "projectPower": {
      "totalPower": 6582.71518,
      "powerRank": 12,
      "round": 2203
    },
    "link": "https://staging.giveth.io/project/syngap-research-fund-srf"
  },
  {
    "id": "929",
    "title": "Tŷ Krishna Cymru",
    "slug": "ty-krishna-cymru",
    "verified": true,
    "projectPower": {
      "totalPower": 6066.063577000001,
      "powerRank": 13,
      "round": 2203
    },
    "link": "https://staging.giveth.io/project/ty-krishna-cymru"
  },
  {
    "id": "915",
    "title": "The Teen Project, Inc.",
    "slug": "the-teen-project-inc",
    "verified": true,
    "projectPower": {
      "totalPower": 5120.094144,
      "powerRank": 14,
      "round": 2203
    },
    "link": "https://staging.giveth.io/project/the-teen-project-inc"
  },
  {
    "id": "910",
    "title": "Desai Foundation",
    "slug": "desai-foundation",
    "verified": true,
    "projectPower": {
      "totalPower": 4311.848526,
      "powerRank": 15,
      "round": 2203
    },
    "link": "https://staging.giveth.io/project/desai-foundation"
  },
  {
    "id": "223518",
    "title": "Alireza Test 2",
    "slug": "alireza-test-2",
    "verified": true,
    "projectPower": {
      "totalPower": 4227.956528000001,
      "powerRank": 16,
      "round": 2203
    },
    "link": "https://staging.giveth.io/project/alireza-test-2"
  },
  {
    "id": "906",
    "title": "Jewish Federation of Northern New Jersey, Inc.",
    "slug": "jewish-federation-of-northern-new-jersey-inc",
    "verified": true,
    "projectPower": {
      "totalPower": 4045.7086399999994,
      "powerRank": 17,
      "round": 2203
    },
    "link": "https://staging.giveth.io/project/jewish-federation-of-northern-new-jersey-inc"
  },
  {
    "id": "913",
    "title": "Primate Rescue Center",
    "slug": "primate-rescue-center",
    "verified": true,
    "projectPower": {
      "totalPower": 2598.835664,
      "powerRank": 18,
      "round": 2203
    },
    "link": "https://staging.giveth.io/project/primate-rescue-center"
  },
  {
    "id": "1108",
    "title": "Children's Tumor Foundation",
    "slug": "childrens-tumor-foundation",
    "verified": true,
    "projectPower": {
      "totalPower": 1751.965608,
      "powerRank": 19,
      "round": 2203
    },
    "link": "https://staging.giveth.io/project/childrens-tumor-foundation"
  },
  {
    "id": "912",
    "title": "Pure Earth",
    "slug": "pure-earth",
    "verified": true,
    "projectPower": {
      "totalPower": 931.8966,
      "powerRank": 20,
      "round": 2203
    },
    "link": "https://staging.giveth.io/project/pure-earth"
  },
  {
    "id": "903",
    "title": "The Discalced Hermits of Our Lady of Mount Carmel",
    "slug": "the-discalced-hermits-of-our-lady-of-mount-carmel",
    "verified": true,
    "projectPower": {
      "totalPower": 422.751667,
      "powerRank": 21,
      "round": 2203
    },
    "link": "https://staging.giveth.io/project/the-discalced-hermits-of-our-lady-of-mount-carmel"
  },
  {
    "id": "916",
    "title": "Zoe Empowers",
    "slug": "zoe-empowers",
    "verified": true,
    "projectPower": {
      "totalPower": 405.85604800000004,
      "powerRank": 22,
      "round": 2203
    },
    "link": "https://staging.giveth.io/project/zoe-empowers"
  },
  {
    "id": "920",
    "title": "The Catholic Foundation of Greater Philadelphia",
    "slug": "the-catholic-foundation-of-greater-philadelphia",
    "verified": true,
    "projectPower": {
      "totalPower": 335.482776,
      "powerRank": 23,
      "round": 2203
    },
    "link": "https://staging.giveth.io/project/the-catholic-foundation-of-greater-philadelphia"
  },
  {
    "id": "921",
    "title": "The Campbell Center",
    "slug": "the-campbell-center",
    "verified": true,
    "projectPower": {
      "totalPower": 271.99376399999994,
      "powerRank": 24,
      "round": 2203
    },
    "link": "https://staging.giveth.io/project/the-campbell-center"
  },
  {
    "id": "223537",
    "title": "Vivy",
    "slug": "vivy",
    "verified": false,
    "projectPower": {
      "totalPower": 0,
      "powerRank": 25,
      "round": 2203
    },
    "link": "https://staging.giveth.io/project/vivy"
  },
  {
    "id": "223535",
    "title": "create project with BNB",
    "slug": "create-project-with-bnb",
    "verified": false,
    "projectPower": {
      "totalPower": 0,
      "powerRank": 25,
      "round": 2203
    },
    "link": "https://staging.giveth.io/project/create-project-with-bnb"
  },
  {
    "id": "223534",
    "title": "Test Tor",
    "slug": "test-tor",
    "verified": false,
    "projectPower": {
      "totalPower": 0,
      "powerRank": 25,
      "round": 2203
    },
    "link": "https://staging.giveth.io/project/test-tor"
  },
  {
    "id": "223533",
    "title": "123go Test",
    "slug": "123go-test",
    "verified": false,
    "projectPower": {
      "totalPower": 0,
      "powerRank": 25,
      "round": 2203
    },
    "link": "https://staging.giveth.io/project/123go-test"
  },
  {
    "id": "223532",
    "title": "multi addresses",
    "slug": "multi-addresses",
    "verified": false,
    "projectPower": {
      "totalPower": 0,
      "powerRank": 25,
      "round": 2203
    },
    "link": "https://staging.giveth.io/project/multi-addresses"
  },
  {
    "id": "223530",
    "title": "testgnosis25",
    "slug": "testgnosis25",
    "verified": false,
    "projectPower": {
      "totalPower": 0,
      "powerRank": 25,
      "round": 2203
    },
    "link": "https://staging.giveth.io/project/testgnosis25"
  }
]
```

**Comment by divine-comedian** [comment]
This looks awesome - then last question is if it is possible in our current system to query ranking by timestamp or by a given GIVbacks round? 

If it's not possible we can leave it until there is a specific demand or use case

**Comment by mohammadranjbarz** [comment]
Unfortunately, we can't have it right now, because we have the power rank data just for the last round in impact-graph DB

> This looks awesome - then last question is if it is possible in our current system to query ranking by timestamp or by a given GIVbacks round?
> 
> If it's not possible we can leave it until there is a specific demand or use case

**Comment by laurenluz** [comment]
@divine-comedian - if you can do some testing, would be great. Need to make sure that the max factor is never ever more than the max (80%).

**Comment by divine-comedian** [comment]
we still have the issue as you mentioned @mohammadranjbarz where the average factor is higher than the max 

![image](https://user-images.githubusercontent.com/67759413/203592807-9a00c245-50e3-4e2d-9dbe-3323359886ca.png)

### These are the params I used:
![image](https://user-images.githubusercontent.com/67759413/203592953-73a10938-bb8b-48a6-8b9e-3333d77b5fe1.png)


----

is there any way to resolve this? is it a problem with the decimal precision?

**Comment by mohammadranjbarz** [comment]
@divine-comedian I just increased the decimal precision in the calculation, so it's fixed now

<img width="749" alt="Screen Shot 1401-09-02 at 19 34 28" src="https://user-images.githubusercontent.com/9850545/203599914-2d63d921-5aa7-48cf-aa62-6677040ddd17.png">

**Comment by divine-comedian** [comment]
@mohammadranjbarz looks good! just one more detail regarding decimal precision

the average GIVback factor needs to have a bit more decimal precision because if we have many projects sometimes the factor could change by < 0.01%

such as this: 

here in eligible donations we can see the percent is 0.7454545455

![image](https://user-images.githubusercontent.com/67759413/203610550-7c9f3907-7991-4bf0-aef4-ebb26135bb05.png)

----

but in the final calculation we only capture up to two decimal places I would recommend adding two more decimal places

![image](https://user-images.githubusercontent.com/67759413/203610901-1b789108-ee6f-4fd2-b8f7-5e673b81c136.png)

**Comment by mohammadranjbarz** [comment]
@divine-comedian  **Done**

<img width="1231" alt="Screen Shot 1401-09-03 at 10 00 48" src="https://user-images.githubusercontent.com/9850545/203715528-6411c6dc-f97b-4da5-9b97-447a13387fa0.png">

**Comment by divine-comedian** [comment]
okay testing again with a wider range of donations I can see now the two amounts = the average of givbacks factor on eligible donations and the amount on the sheet don't match up

![image](https://user-images.githubusercontent.com/67759413/203846976-5e222f59-ae19-435d-a100-b6ccd80c45a9.png)

![image](https://user-images.githubusercontent.com/67759413/203847106-ba446056-b65f-4e17-b401-ddf917a718c6.png)
![image](https://user-images.githubusercontent.com/67759413/203847246-93a35fc0-6e5a-4d91-9184-8b5cc11859e0.png)

I think it's because it is fetching the current rank of the project and not the rank of the project at the time the donation was made - am I correct?

**Comment by divine-comedian** [comment]
From our chat @mohammadranjbarz 

We need to be able to have the historical GIVpower rank data for each donation in order to accurately calculate the givbacks factor. 

- [ ] save projectRank and bottomRank (the lowest rank) at time of donation for each donation
- [ ] move the max factor and min factor as internal variables in the backend. so we can use them to make calculations at time of donation
- [ ] calculate somewhere the givbacks factor for each donation at time of donation based on the two variables saved above
- [ ] update the API information with new information sources for both `calculate` and `eligible-donations`

**Comment by mohammadranjbarz** [comment]
> From our chat @mohammadranjbarz
> 
> We need to be able to have the historical GIVpower rank data for each donation in order to accurately calculate the givbacks factor.
> 
> * [x]  save projectRank and bottomRank (the lowest rank) at time of donation for each donation
> * [x]  move the max factor and min factor as internal variables in the backend. so we can use them to make calculations at time of donation
> * [x]  calculate somewhere the givbacks factor for each donation at time of donation based on the two variables saved above
> * [x]  update the API information with new information sources for both `calculate` and `eligible-donations`

@divine-comedian  I did all above items now you can test it again, the response for eligible donations is something like this for new donations (current just my donation has these variables)

```
 {
    "amount": 0.01,
    "currency": "XDAI",
    "createdAt": "2022-11-30-09:21:11",
    "valueUsd": 0.01,
    "bottomRankInRound": 20,
    "powerRound": 3146,
    "projectRank": 2,
    "givbackFactor": 0.7842105,
    "valueUsdAfterGivbackFactor": 0.0078421,
    "giverAddress": "0x5ac583feb2b1f288c0a51d6cdca2e8c814bfe93b",
    "txHash": "0x154cc29799aae49c962e50fd50f73b9d316da7b3582fa2deab1569b7356e4e47",
    "network": "xDAI",
    "source": "giveth.io",
    "giverName": "Mohammad Ranjbar",
    "giverEmail": null,
    "projectLink": "https://giveth.io/project/how-many-photos-is-too-many-photos"
  }
```

And these values come from impact-graph

```
    "bottomRankInRound": 20,
    "powerRound": 3146,
    "projectRank": 2,
    "givbackFactor": 0.7842105,
```

but for old donations that don't have this field you would see

```
{
    "amount": 0.001,
    "currency": "ETH",
    "createdAt": "2022-11-24-09:13:44",
    "valueUsd": 1.19823,
    "bottomRankInRound": null,
    "powerRound": null,
    "projectRank": null,
    "givbackFactor": 0.5,
    "valueUsdAfterGivbackFactor": 0,
    "giverAddress": "0x871cd6353b803ceceb090bb827ecb2f361db81ab",
    "txHash": "0x3ba96b6d8592e925758d75883b8068bf4babbb677fb296cb2cfe8c5170760dec",
    "network": "xDAI",
    "source": "giveth.io",
    "giverName": "Alireza Sharifpour",
    "giverEmail": null,
    "projectLink": "https://giveth.io/project/the-discalced-hermits-of-our-lady-of-mount-carmel"
  }
```
I put `0.5` by default for those donations but if you have other idea for that case please tell me

**Comment by divine-comedian** [comment]
> > @mohammadranjbarz if the donations were made before GIVpower ranking then the default givbackFactor should be 0.75
> > Also what is the powerRound? the current GIVpower staked?
> 
> @divine-comedian
> 
>     1. default givbackFactor has been changed to `0.75`
> 
>     2. powerRound is the round that donations are made on that, technically it would same for all donations of each round ( if you think the name is confusing I can change it)

following our convo in discord - keep logic the same and I would suggest changing the name of `powerRound` to `givbacksRound` so the reference is more clear

**Comment by mohammadranjbarz** [comment]
> > > @mohammadranjbarz if the donations were made before GIVpower ranking then the default givbackFactor should be 0.75
> > > Also what is the powerRound? the current GIVpower staked?
> > 
> > 
> > @divine-comedian
> > ```
> > 1. default givbackFactor has been changed to `0.75`
> > 
> > 2. powerRound is the round that donations are made on that, technically it would same for all donations of each round ( if you think the name is confusing I can change it)
> > ```
> 
> following our convo in discord - keep logic the same and I would suggest changing the name of `powerRound` to `givbacksRound` so the reference is more clear

Done.

**Comment by divine-comedian** [comment]
so there is an issue here in that when the total givbacks calculated is great than the maximum (1 million GIV tokens) we need to reduce the matching GIVbacks amount and the actual GIVbacks Factor 

I did write these formulas already in the spreadsheet simulator here - you can see in the tab `actual data` how this would apply to the current calculate API:
https://docs.google.com/spreadsheets/d/1yz_6sgFmEXgGU9BgeRtgVALQlNFWJMUkxddpTlG2Krs/edit?usp=sharing

here is a clear copy of those formulas:


**IF total GIVbacks is over the threshold we make the following calculation for each recipient:**

ACTUAL GIVBACKS = MAXIMUM TOTAL GIVBACKS PER ROUND * ( ESTIMATED GIVBACKS / TOTAL GIVBACKS ESTIMATED)

-----

**new GIVbacks Factor % is calculated by:**
NEW GIVBACKS FACTOR = (ACTUAL GIVBACKS *  PRICE OF GIV TOKEN) / USD VALUE OF DONATION

**Comment by divine-comedian** [comment]
tested on https://givback.develop.giveth.io/staging/api-docs/#/default/get_calculate

tested scenarios
- users donating to multiple ranked projects across multiple rounds 
- users donating to projects with different ranks 
- ensured historical ranking is captured & givbacks factor is correct in one round to the next if the actual rank changes
- average givbacks factor is calculated correctly for a user who has made multiple donations to different ranked projects
- if the estimated givbacks is over the maximum we lower the givbacks factor accordingly

i think this API is ready to go!
