### ISSUE TITLE
Donation amounts not matching / don't make sense

### ISSUE THREAD

**Issue by clara-zi** [Giveth/giveth-dapps-v2#1891]
This project owner has only 1 project but is showing a different total donations amount in profile and project page. Is it a bug or am I missing something?

$400k in personal and $480k in project.

![image.png](https://images.zenhubusercontent.com/6228be80d06a422295d2247f/f33e57f3-4938-43cb-9a3c-9ef89850d5b1)

**Comment by MoeNick** [comment]
@CarlosQ96 do you know what's the difference of these 2 queries?

**Comment by CarlosQ96** [comment]
I fixed something related two weeks ago. They are project totals that are recalculated after every donation. It was working fine... I validated with Ashley. 
After doing some donations it seems the bug is only in the recalculation of user total. I checked logs and found nothing.

**Comment by CarlosQ96** [comment]
Project total recalculation is working fine, tho.

@MoeNick I feel those queries are inefficient, so the issue might be there but I couldn't find any other clue. 

They do 6 queries total. I think I can reduce this to 2. Less code, more memory efficient. 
Will continue on this tomorrow.

**Comment by CarlosQ96** [comment]
@MoeNick Actually today I checked an its fixed!
<img width="1458" alt="image" src="https://user-images.githubusercontent.com/92376054/206230490-89e199cf-1992-4d30-84bc-04f22f7f08ee.png">

Like I said I fixed this two weeks ago. So it's taking a while to reflect the value, but I don't know why.

This is the database after donating 1 Dai to Unchained project.
<img width="347" alt="image" src="https://user-images.githubusercontent.com/92376054/206291925-3c9b4cd2-9c97-464c-8aee-02e0c84f28db.png">

But UI shows. 
<img width="675" alt="image" src="https://user-images.githubusercontent.com/92376054/206292062-0eb331a2-9360-47b0-87b8-495c4b0ebd08.png">

**Comment by CarlosQ96** [comment]
@RamRamez @MohammadPCh does the frontend has some sort of cache? that its not allowing the value to change?

**Comment by CarlosQ96** [comment]
This is only ocurring the user profile page on the total Received.

**Comment by CarlosQ96** [comment]
Even the query from graph returns the correct value: (I donated another dai)
<img width="1252" alt="image" src="https://user-images.githubusercontent.com/92376054/206293735-d08e13f3-5b6a-4e76-924d-30996c0bf159.png">
But UI keeps showing after refreshing:
<img width="1347" alt="image" src="https://user-images.githubusercontent.com/92376054/206293854-ee2a8294-c9d9-4b0b-90ff-d2a9c4851d97.png">

**Comment by CarlosQ96** [comment]
So I think there is some sort of frontend cache @MoeNick , the api and database are returning the correct value.

**Comment by CarlosQ96** [comment]
Seems like an 8-10 min cache

**Comment by RamRamez** [comment]
@CarlosQ96 There's no cache on front-end. I did some testing on Goerli network and the total donation received was instantly updated (even when tx is not mined yet, total donation is updated).

![image](https://user-images.githubusercontent.com/73441857/206438615-888e7763-5e5a-4975-a672-0e74b5707f70.png)

@clara-zi Can you send me the user wallet address? are on staging or production?

**Comment by CarlosQ96** [comment]
@RamRamez here is the user https://giveth.io/user/0xd6cd2bcaf88e8bf39652d65091fe05715c7ce1e1
This is production.

**Comment by RamRamez** [comment]
Thank you @CarlosQ96 for your help. I found the problem.
Fixed in PR #1920

**Comment by MoeNick** [comment]
@maryjaf please take a look and approve it.

**Comment by maryjaf** [comment]
<img width="1411" alt="image" src="https://user-images.githubusercontent.com/111529185/213930105-18746dfc-5825-42bd-bba0-2e8ca36814ee.png">
I tested this scenario on stg and It seems that the problem is not solved
@RamRamez

**Comment by RamRamez** [comment]
> <img alt="image" width="1411" src="https://user-images.githubusercontent.com/111529185/213930105-18746dfc-5825-42bd-bba0-2e8ca36814ee.png">
> 
> I tested this scenario on stg and It seems that the problem is not solved https://staging.giveth.io/user/0xcd192b61a8dd586a97592555c1f5709e032f2505?tab=projects
> @RamRamez

I fixed it in PR #2095. Now small donations of less than 0.5$ will be shown as zero on project cards.
BTW, the total amount is still wrong for this project:
http://localhost:3000/project/tests

That's because you've changed total donations via admin bro but actually, there are no donations.
![image](https://user-images.githubusercontent.com/73441857/214838335-cd4c4c84-4bba-48b8-9e08-4edc505833bb.png)

**Comment by maryjaf** [comment]
I donate below project (0.6) but still the denation of this project is shown 0 on project card,Plz check @RamRamez 
<img width="487" alt="image" src="https://user-images.githubusercontent.com/111529185/215017316-535b115c-186d-49c6-88a8-ea53eb456eb8.png">
https://staging.giveth.io/project/maryams-test

**Comment by RamRamez** [comment]
@maryjaf You've donated 0.6 GIV which equals 0.011 USD. In project cards USD amount is projected.
![image](https://user-images.githubusercontent.com/73441857/215070185-639234c8-9c12-4ce9-8b7a-0a58509bc83d.png)

**Comment by maryjaf** [comment]
> than 0.5$ will be shown

I thought there the  amount unit is GIV
Thanks @RamRamez this issue has been passed
