### ISSUE TITLE
Improve Estimated matching calculations

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2886]
we should add a "cap" of 20% of the matching pool to our estimated matching calculations.

So, the max matching that any project can get is 20% of the matching pool. For the alpha round. max matching is $2000 (based on the matching pool of $10k)

@CarlosQ96 @mohammadranjbarz - can you implement this?

cc @maryjaf @MoeNick

**Comment by alireza-sharifpour** [comment]
Hey @laurenluz 
I updated our code, this is our previous calculations :
<img width="321" alt="Screenshot 2023-07-12 at 6 43 32 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/48887817/e32ac7f3-c07c-4b76-b26b-dfc68b04efd0">
And this is after these changes:
<img width="339" alt="Screenshot 2023-07-12 at 6 44 15 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/48887817/417f4119-cd03-4692-95f7-d04a7245cbd7">

Here no project can get more than 20 percent of total allocation, for example for this round the total is 10000$ and here you can see in the picture that this project won't be able to get more than 2000$ Matching in total.
is it ok @laurenluz ?

CC: @aminlatifi @MohammadPCh

**Comment by laurenluz** [comment]
yes!! that's great! once we merge it we can get @maryjaf to retest

**Comment by maryjaf** [comment]
> yes!! that's great! once we merge it we can get @maryjaf to retest

Thanks guys 
I'll test this more tonight & tomorrow

**Comment by laurenluz** [comment]
hey guys... there is an issue with the estimate matching on staging. I think maybe there was some confusion around how this should be calculated... 

we need to consider that even if the estimated matching on a particular project is at the "cap" (20% of our total matching pool)... a new donation will still have some associated matching.

for example.. if a project has $2000 estimated matching and 2 donors who already donated $1 each... we can say that each donor's matching is $1000.

Then... if a new user is thinking about donating $1 to that project... we would say that user's estimated matching is $667 (i.e. 2000/3)... because their new donation would be associated with 1/3 of the total matching the project gets in the end.

The match will get a little more complicated if we have like 2 donors of $50 and 1 donor of $10 and a new donor considering to donate $1... but basically... every donation should always have SOME estimated matching. does it make sense?

@aminlatifi can you help with @alireza-sharifpour ?

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/213bb4da-4fd2-4554-8112-191d4726cc61)

**Comment by maryjaf** [comment]
When a project receives 20% of fund in around , then the estimate matching shows 0. Is this behavior expected? @laurenluz @aminlatifi 
<img width="1338" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/a9de790b-e151-4794-b231-c4bdb1c89db9">

**Comment by laurenluz** [comment]
also... we should be using this logic in all the estimated matching calculations... we can't just say that the new donor is associated with 100% of the change of matching after their donation... because it's not a fair proportion.

So basically... when we are not at the cap... to calculate the esimated matching...
1. we should pretend like this new user is making a donation of $1 to the project.
2. then we consider the total matching that will be allocated to that project after the new donation
3. then we look at that new users donation, and compare it with the size of the donations of other users (and the impact of QF formula that each of those donations has on the total matching...)
4. then we can say the impact of the user's matching is some proportion of the total change of matching... and the $ value is the user's estimated matching.

or something like that... I'm trying to work towards a good logic here and can use your help @aminlatifi because we also need to keep in mind the quadratic formula.

**Comment by aminlatifi** [comment]
> hey guys... there is an issue with the estimate matching on staging. I think maybe there was some confusion around how this should be calculated...
> 
> we need to consider that even if the estimated matching on a particular project is at the "cap" (20% of our total matching pool)... a new donation will still have some associated matching.
> 
> for example.. if a project has $2000 estimated matching and 2 donors who already donated $1 each... we can say that each donor's matching is $1000.
> 
> Then... if a new user is thinking about donating $1 to that project... we would say that user's estimated matching is $667 (i.e. 2000/3)... because their new donation would be associated with 1/3 of the total matching the project gets in the end.
> 
> The match will get a little more complicated if we have like 2 donors of $50 and 1 donor of $10 and a new donor considering to donate $1... but basically... every donation should always have SOME estimated matching. does it make sense?
> 
> @aminlatifi can you help with @alireza-sharifpour ?
> 
> ![image](https://user-images.githubusercontent.com/75490971/253346053-213bb4da-4fd2-4554-8112-191d4726cc61.png)

I am not sure considering that will not cause more issues.
In the design, there is a plus besides the estimate matching value, so it conveys this message that the new donation will add to the project reward which will not actually.
I suggest  adding some tooltip when the estimate matching is zero and say this project's estimate matching will reach/has reached to the max possible value

**Comment by laurenluz** [comment]
if we say "this project has reached the max possible" it will disincentivize people to donate... and falsely... because it will not get the max. maybe it's just got the max because there have only been 2 donations!!

if 100 people donate to another project, it will get very little...

I do hear wht you're saying on the "+x DAI"... but I think it's better to change the logic to make the numbers more accurate.. consider the "estimated matching for a donation" to be like the proportional matching that the project gets as a result of that user's donation.

**Comment by laurenluz** [comment]
I think it can be tested now @maryjaf

**Comment by maryjaf** [comment]
> "estimated matching for a donation" to be like the proportional matching that the project gets as a result of that user's donation.
Thanks @aminlatifi 
Now when a user tries to donates to a project  that  it has a maximum of the amount of fund (in this example 2000 ) the estimated matching is shown in project page view and donation page as below pic
<img width="1431" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/d1d48a9c-b06b-46cd-8de1-7c9adfadbc3e">
<img width="1287" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/923fc9d6-c084-44ca-8fe0-2e1b492b95e7">

and after completing the donation,  the estimated matching for this project remains 2000 like before , is this the expected behavior of system  ?‌ @laurenluz

**Comment by laurenluz** [comment]
yes! @maryjaf - since the estimated matching of the project is at the cap ($2000) - it can never be estimated to be more than that.
However, we can still show that there is some estimated matching associated with the user's donation... we consider this estimate to be... the amount of matching associated with a donation of that size. (like we look at the weight of the new donation and what amount of the total matching would be associated with that donation)

**Comment by maryjaf** [comment]
Thanks @aminlatifi This issue has been resolved
