### ISSUE TITLE
Allow to set the matching pool token & amount to be something other than USD

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3839]
for many rounds, we will have matching pools in tokens beyond USD...

MATIC, mpETH, USDGLO, DAI, etc...

To date, all our matching pools are set as "matching pool amount in USD" - in admin bro & in the backend, and this number is used for a variety of other things including
- estimated matching
- project weight & final matching in data export
- round stats (#3674)

I would like to be able to choose a chain & a token for the matching pool (and have this set in our backend) and then set the amount in that token. We will need to consider then that we should fetch the price of the token when showing estimated matching etc.

I think this is a backend first issue.

@jainkrati

**Comment by jainkrati** [comment]
@CarlosQ96 pls pick this once your p0,p1 issues are done

**Comment by laurenluz** [comment]
bumping the priority here, would love this to get done before our next qf round!

**Comment by laurenluz** [comment]
can we make this a priority? for the polygon round, I'd love to put the "matching funds" in the db as... MATIC...

is that going to be crazy? @CarlosQ96 😇

**Comment by CarlosQ96** [comment]
Im estimating this issue and will leave my estimation here tomorrow morning. I have to check if there is any side effect in the different codes like the weight/distributions.

**Comment by CarlosQ96** [comment]
I feel this can work, but we should set a display setting. Because we save in the database BOTH the USD value and the token amount.
So it depends on what we want to show to the user. 

Would require frontend to read this setting and choose the appropiate column to display. 
But just adding it, can be 1 hour at most. If this is the way we want it. @laurenluz

**Comment by jainkrati** [comment]
@laurenluz pls confirm if we can go ahead with what carlos proposed above. 

Adding @RamRamez for FE changes once @CarlosQ96 has implemented the BE changes.

**Comment by jainkrati** [comment]
@laurenluz waiting on you to confirm

**Comment by laurenluz** [comment]
yeah that sounds fine. so we would set in admin bro if we want to show the USD value or the token value in that case?

and in admin bro the user would set the matching pool token & amount in that token? (rather than the USD value as we have it now?? @CarlosQ96 @RamRamez

**Comment by RamRamez** [comment]
I added "allocated Token Symbol" and "allocated Token Chain Id" in AdminJS that allows us to set for new QF rounds.
@laurenluz what about past QF rounds? maybe we can set USDT and token chain for them manually.

**Comment by laurenluz** [comment]
Re: your comment in the discord:

> What changes do you need on FE? Replacing the dollar sign with token symbol for estimated matching would be enough?

Yes! On the frontend, actually we need to consider several places... Right now, there are even bugs in what we show.... we are showing estimated matching table in DAI, when the round is not necessarily in DAI....

On donate page (should say "$amount" or "amount tokenname")
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/010d0a9d-fb6f-4943-8cd6-34addec50274)

On project single page (should say $amount" or "amount tokenname" in both the estaimted matching total amounts... and in the table, where right now it is saying DAI.. it should only say DAI if the token is DAI for that round)
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/9d71dab5-df1d-4105-9119-607c99c17d8b)

On project single page donate tab, qf round subtab: (should say "$amount" or "amount tokenname")
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/7965e8d1-5699-4716-bf17-13e53fed9704)

On project card: (should say "$amount" or "amount tokenname")
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/a4a4953d-590b-4b0b-b6f5-d8ed410f2b04)

> @laurenluz what about past QF rounds? maybe we can set USDT and token chain for them manually.

If we have some kind of input field in adminJS where admin can set the matching pool amount, token.... I can retroactively edit the past rounds. Ideally, I could input:
- matching pool amount (in token)
- token symbol
- token chain id

... and then the USD value of the matching pool amount is fetched using price discovery from our backend...
but if the price fetching will be too challenging... we can also have a field where admin inputs the USD amount for the matching pool (they can look it up and approximate).

Ideally, we could have the option if the admin wants to show the matching pool in the Token... or show the USD value instead.

wdyt @RamRamez ? cc @koday1

**Comment by RamRamez** [comment]
@laurenluz token Is QF token chain id used anywhere? I've already added that field to QFRound, I'm just asking for clarification.

**Comment by laurenluz** [comment]
I don't think it is... but I would love to use it in our qf round data export because atm... I need to filter through many addresses for each project to find the one to send matching funds to (as a new column)

Just fyi @CarlosQ96

**Comment by jainkrati** [comment]
@RamRamez can you take up the FE changes for this as well

**Comment by RamRamez** [comment]
> @RamRamez can you take up the FE changes for this as well

I'm on it

**Comment by RamRamez** [comment]
Done! @laurenluz Please check and approve this feature branch.

https://vercel.live/open-feedback/giveth-dapps-v2-git-allow-to-set-the-matching-p-c4890a-givethio.vercel.app?via=pr-comment-visit-preview-link&passThrough=1

**Comment by laurenluz** [comment]
oh I don't have an ability to lock into this verson of admin bro - it's different from prod. Do I need to set something up for it specifically? @RamRamez 
(I've never set up admin bro login for staging)

**Comment by laurenluz** [comment]
Thanks for helping me set up the login @RamRamez!! Testing now, here's the bugs I'm finding:

AllocatedFund = 10k MATIC
USD value = $80k

## When set to show USD value:

- [ ] On the stats banner (when I'm set to show the allocated fund in USD)... this should show $80,000 (for some reason, it didn't change when I updated admin bro):
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/2a6481c9-63a8-4843-b10d-837d49f7a653)

- project card looks good
- project single page "card" looks good, both in the estimate matching table & the big value
- project single page donation tab for the round looks good

## When set to show MATIC value:

- [ ] On the QF stats banner (when I'm set to show the allocated fund in MATIC)... this should show 10,000 MATIC
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/3675c36a-9c3d-42fa-93d6-769b4f015171)

- project card looks good
- project single page "card" looks good, both in the estimate matching table & the big value
- project single page donation tab for the round looks good

If you are fixing things on that banner @RamRamez maybe you can also address this rounding issue on the stats banner...

- [ ] This should show up to 2 decimal places... i.e. $693.67
<img width="1413" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/75490971/65a36888-00fb-470f-8098-a634a3aa65aa">

**Comment by RamRamez** [comment]
> Thanks for helping me set up the login @RamRamez!! Testing now, here's the bugs I'm finding:
> 
> AllocatedFund = 10k MATIC USD value = $80k
> 
> ## When set to show USD value:
> * [x]  On the stats banner (when I'm set to show the allocated fund in USD)... this should show $80,000 (for some reason, it didn't change when I updated admin bro):
>   ![image](https://private-user-images.githubusercontent.com/75490971/327808736-2a6481c9-63a8-4843-b10d-837d49f7a653.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3NTU2NDEsIm5iZiI6MTcxNDc1NTM0MSwicGF0aCI6Ii83NTQ5MDk3MS8zMjc4MDg3MzYtMmE2NDgxYzktNjNhOC00ODQzLWIxMGQtODM3ZDQ5ZjdhNjUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAzVDE2NTU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhYzQ0Y2JkYmMxMTFhYzFlYTUxZjAxOWNkNDFmMTdmZmE1MWViNzBjYzBkMWU2OTRmMzA4ZWY1N2U1YzBkOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7N1KYgBEDxqav9XQdLHX7hrXH0_B3Kmbe4TyRy6IiHo)
> * project card looks good
> * project single page "card" looks good, both in the estimate matching table & the big value
> * project single page donation tab for the round looks good
> 
> ## When set to show MATIC value:
> * [x]  On the QF stats banner (when I'm set to show the allocated fund in MATIC)... this should show 10,000 MATIC
>   ![image](https://private-user-images.githubusercontent.com/75490971/327808680-3675c36a-9c3d-42fa-93d6-769b4f015171.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3NTU2NDEsIm5iZiI6MTcxNDc1NTM0MSwicGF0aCI6Ii83NTQ5MDk3MS8zMjc4MDg2ODAtMzY3NWMzNmEtOWMzZC00MmZhLTkzZDYtNzY5YjRmMDE1MTcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAzVDE2NTU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4ODZmYTlmM2U2ODk5YzNjMThlYjlhNTcxMTFhYWE5MWQwODA5YjlkYzQ3NjBkN2U5M2Y1MTcwYmMzYjg3ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Yv9APxvAvegubyjlilkCn1YTStDYJOgM6tcNrLx92d0)
> * project card looks good
> * project single page "card" looks good, both in the estimate matching table & the big value
> * project single page donation tab for the round looks good
> 
> If you are fixing things on that banner @RamRamez maybe you can also address this rounding issue on the stats banner...
> 
> * [x]  This should show up to 2 decimal places... i.e. $693.67
> 
> <img alt="image" width="1413" src="https://private-user-images.githubusercontent.com/75490971/327813539-65a36888-00fb-470f-8098-a634a3aa65aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3NTU2NDEsIm5iZiI6MTcxNDc1NTM0MSwicGF0aCI6Ii83NTQ5MDk3MS8zMjc4MTM1MzktNjVhMzY4ODgtMDBmYi00NzBmLTgwOTgtYTYzNGEzYWE2NWFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAzVDE2NTU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzYzdjYmYzZGY2ZTQ3YTI1NjgwYjcxNDAxMmI2Y2FlNzViNDM3ZjQ2YzI1NWJmNGUxMmMxOWU3YTc4MzA1NzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9mfDIMJCTnMVXY9u2g-HJ-LiKUXrIVprpBb77tKvvhQ">

@laurenluz Thanks for testing.
Done!

**Comment by laurenluz** [comment]
Looks great! I just checked again, and didn't see any issues on the preview.

**Comment by RamRamez** [comment]
@maryjaf to test and verify

**Comment by maryjaf** [comment]
please take a look on below video @RamRamez 

- In the first step, the QF round data in admin is set on MATIC
-Then  I've checked the box : Allocated Fund USD Preferred
- after refreshing QF page,  the "Galactic Giving Metrics" has been updated correctly and 80000$ is shown 
- but the other items is shown based on matic and after second refreshing it has been fixed

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/ea27c86e-0a04-4174-8d76-a6c351a7f59b

**Comment by RamRamez** [comment]
@maryjaf project cards need about 1 minute before refresh, I think it's ok because it's only set once for each QF round.

**Comment by koday1** [comment]
@maryjaf @RamRamez Do you know when this will be merged to prod? Glo Dollar is asking if we can change the matching estimate table from DAI to USDGLO, this issue will allow that and I am hoping to provide them with a date when it will be available. Thanks in advance

**Comment by RamRamez** [comment]
@jainkrati @divine-comedian can we have a release for FE and BE soon to make this feature live?

**Comment by laurenluz** [comment]
on prod I'm seeing an issue in admin bro now trying to edit the round:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/4c91a17d-941b-422c-b1a3-0077fab52673)

**Comment by Meriem-BM** [comment]
@RamRamez I guess it's related to her role? can you confirm what role is that email registered with on prod.

**Comment by RamRamez** [comment]
@Meriem-BM her role is "admin" so he must be able to edit, I can't edit that page too with my own account, I had access before tho.
I tested master branch locally and it allows me to edit the QF round, so I think there's no problem with codes

**Comment by Meriem-BM** [comment]
I see so there must be an error that appears on deployed prod, can you share with me the prod link and an account to test @RamRamez

**Comment by koday1** [comment]
@RamRamez @Meriem-BM Checking in here, any updates from last week? Have we tested this further? 

Cc @laurenluz

**Comment by maryjaf** [comment]
I've tested again on production and I didn't see the authorization error on edit page again,  it seems it has been resolved .
Do you also confirm that it is solved? @laurenluz

**Comment by laurenluz** [comment]
I'm not getting the error on production, but also... this isn't working as expected. @RamRamez @maryjaf 

I set this for galactic giving round:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/931d2330-7389-4469-a5e3-6f72539f6acb)

but I still see all the values in USD or DAI

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/73ac6f82-2b10-47f3-a9d4-cda294b022e9)

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/3ef33df5-e016-4d4b-964b-c4fe5a0e1a45)

Is this because the round was set up before we pushed this fix?

**Comment by maryjaf** [comment]
> Is this because the round was set up before we pushed this fix?

No, on stg it works also for rounds that was set up before, it seems there is a problem on prod @RamRamez 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/347a543f-738e-461c-824c-4566bf079244)

**Comment by RamRamez** [comment]
@laurenluz this is not on production yet, it's only on staging as we talked before.
If you need this, I can prepare a cherry-pick for release.

**Comment by laurenluz** [comment]
but it is on production @RamRamez 🤔 the bug I had before was on prod... now there is no bug, but it doesn't work as expected.

Krati told me like last week that you guys merged & @maryjaf & I have been checking prod.

**Comment by RamRamez** [comment]
> but it is on production @RamRamez 🤔 the bug I had before was on prod... now there is no bug, but it doesn't work as expected.
> 
> the screenshot I shared editing the round - that's all from admin bro in prod.
> 
> Krati told me like last week that you guys merged & @maryjaf & I have been checking prod.
> 
> Is admin bro up to date, but it's not supposed to be controlling things on the FE on prod? or how is this working?

@laurenluz backend is merged on production so you can see the new fields are added in AdminJS but frontend not merged yet so it won't apply the changes.

**Comment by laurenluz** [comment]
ooh I see.

**Comment by RamRamez** [comment]
@laurenluz this feature is now live on production, you set custom tokens for matching pools, also you can define QF round banner and sponsors from AdminJS. Besides that, you can fill "Allocated Fund USD" and "Allocated Token Symbol" fields for previous QF rounds using AdminJS to show in [/qf-archive](https://giveth.io/qf-archive) page
