### ISSUE TITLE
Add GIV on polygon zkEVM to GIVbacks eligible tokens

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4680]
not there yet!

https://zkevm.polygonscan.com/token/0xddAFB91475bBf6210a151FA911AC8fdA7dE46Ec2

@divine-comedian do you know how can do this?

![image](https://github.com/user-attachments/assets/63b4a903-58ef-469e-8b08-f69c2b3ff8b1)

**Comment by divine-comedian** [comment]
Done! 
![image](https://github.com/user-attachments/assets/44d9f778-052c-4345-baae-44b8be8b2b6e)

**Comment by laurenluz** [comment]
wow you are so cool, omg

**Comment by laurenluz** [comment]
is there something else that needs to happen to get price discovery? 
![image](https://github.com/user-attachments/assets/924b5acd-c9cb-4fad-98cf-c2f7bf7c22a8)

**Comment by laurenluz** [comment]
@divine-comedian ? wdyt about the price discovery? this issue still persists

**Comment by divine-comedian** [comment]
Looks like it only affects zkEVM! perhaps it is related to a subgraph issue for fetching the GIV price. it works for gnosis and OP

**Comment by mohammadranjbarz** [comment]
<img width="1451" alt="Screenshot 1403-07-05 at 2 00 51 in the afternoon" src="https://github.com/user-attachments/assets/a22f5d8c-2ccd-48f7-8c23-41a615444750">

@laurenluz  @divine-comedian  @maryjaf 

I deployed the hotfix and it's working now

**Comment by maryjaf** [comment]
![image](https://github.com/user-attachments/assets/48951444-1a1d-4d9d-a2e7-b0e7c8358d5f)
